ALTER SESSION  SET "_ORACLE_SCRIPT" = TRUE; 

CREATE USER BD_Farmacia IDENTIFIED BY admin

DEFAULT TABLESPACE users

TEMPORARY TABLESPACE temp

QUOTA UNLIMITED ON users;

CREATE ROLE ADMINISTRADORES;

GRANT CREATE SESSION, CREATE ANY TABLE, CREATE ANY PROCEDURE, ALTER ANY TABLE, ALTER ANY PROCEDURE, DROP ANY TABLE, DROP ANY PROCEDURE TO ADMINISTRADORES;

GRANT ADMINISTRADORES TO BD_Farmacia;

---CONSULTA PARA VERIFICARLOS ROLES CREADOS

SELECT * FROM DBA_ROLES;

---CONSULTA PARA VARIFICAR LOS PRIVILEGIOS ASIGNADOS A UN ROL

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='ADMINISTRADORES';

CREATE TABLE Persona (
    ID_Persona int
);

INSERT INTO Persona 
VALUES (1);

DROP TABLE Persona


